import { galleryPhoto, assignUniqueCovers } from '../../media/gallery.js';

function day(iso, day, dateLabel, title, body, extra = {}) {
  return {
    iso,
    day,
    dateLabel,
    title,
    body,
    stay: extra.stay || 'Own arrangements / onward transfer',
    viewing: extra.viewing || 'Game drive',
    transport: extra.transport || 'Shared 4x4 safari vehicle',
    meals: extra.meals || 'Breakfast, lunch and dinner',
    image: extra.image || galleryPhoto('tarangire', 0),
  };
}

export const openJoiningPackages = [
  {
    id: '3-days-affordable-joining-safari',
    slug: '3-days-affordable-joining-safari',
    title: '3 Days Affordable Joining Safari',
    datesLabel: 'Open 2026–2027',
    start: '',
    end: '',
    duration: '3 Days / 2 Nights',
    places: 'Tarangire · Ngorongoro · Lake Manyara',
    image: galleryPhoto('tarangire', 0),
    style: 'wildlife',
    activity: 'Group Safari',
    featured: false,
    price_from: 800,
    currency: 'USD',
    spaces: 'Shared vehicle · lodge nights',
    deposit: 'Join group',
    tags: [
      { label: 'Tarangire', detail: 'Baobabs and elephants' },
      { label: 'Ngorongoro Crater', detail: 'Full crater game drive' },
      { label: 'Lake Manyara', detail: 'Final morning' },
    ],
    overview:
      'A three-day shared safari from Arusha covering Tarangire, Ngorongoro Crater, and Lake Manyara. You travel in a shared 4x4 with a professional English-speaking guide and stay two nights in lodge accommodation.',
    cta: 'Ask to join this 2026–2027 group safari — USD 800 per person.',
    highlights: [
      'Three Northern Circuit parks',
      'Shared 4x4 and professional guide',
      'Two nights lodge accommodation',
      'Park and crater fees included',
    ],
    included: [
      'Park entry fees and Ngorongoro crater fees',
      'Shared 4x4 safari vehicle',
      'Professional English-speaking guide',
      '2 nights budget lodge accommodation',
      'Meals as specified',
      'Drinking water on game drives',
    ],
    excluded: [
      'International flights and Tanzania visa',
      'Travel insurance',
      'Drinks, tips, and personal expenses',
      'Optional activities',
    ],
    days: [
      day('', 'Day 1', 'Open departure', 'Tarangire National Park', 'Morning pickup in Arusha, then a full day in Tarangire among baobabs and seasonal wildlife. Picnic lunch in the park, then lodge overnight.', {
        stay: 'Fig Tree Lodge',
        meals: 'Lunch and dinner',
        viewing: 'Full-day game drive',
        image: galleryPhoto('tarangire', 1),
      }),
      day('', 'Day 2', 'Open departure', 'Ngorongoro Crater', 'Descend to the crater floor for a game drive across grassland, woodland, and wetlands. Picnic lunch, then return to the lodge.', {
        stay: 'Fig Tree Lodge',
        viewing: 'Crater game drive',
        image: galleryPhoto('ngorongoro', 0),
      }),
      day('', 'Day 3', 'Open departure', 'Lake Manyara and return to Arusha', 'Morning game drive in Lake Manyara, lunch, then drive back to Arusha for hotel drop-off.', {
        stay: 'Own arrangements / onward transfer',
        meals: 'Breakfast and lunch',
        viewing: 'Morning game drive',
        image: galleryPhoto('ngorongoro', 6),
      }),
    ],
  },
  {
    id: '4-days-shared-safari-tanzania',
    slug: '4-days-shared-safari-tanzania',
    title: '4 Days Shared Safari Tanzania',
    datesLabel: 'Open 2026–2027',
    start: '',
    end: '',
    duration: '4 Days / 3 Nights',
    places: 'Tarangire · Serengeti · Ngorongoro',
    image: galleryPhoto('serengeti', 0),
    style: 'wildlife',
    activity: 'Group Safari',
    featured: true,
    price_from: 1000,
    currency: 'USD',
    spaces: 'Shared vehicle · two Serengeti nights',
    deposit: 'Join group',
    tags: [
      { label: 'Serengeti', detail: 'Two nights in the park' },
      { label: 'Tarangire', detail: 'Opening game drive' },
      { label: 'Ngorongoro', detail: 'Final crater day' },
    ],
    overview:
      'A four-day joining safari from Arusha: Tarangire, two nights in the Serengeti, and a Ngorongoro Crater game drive before you return to town. Shared 4x4, professional guide, and budget lodge or public-campsite nights as listed.',
    cta: 'Ask to join this 2026–2027 group safari — USD 1,000 per person.',
    highlights: [
      'Two nights in the Serengeti',
      'Tarangire and Ngorongoro Crater',
      'Shared 4x4 and professional guide',
      'Park and crater fees included',
    ],
    included: [
      'Park entry fees and Ngorongoro crater fees',
      'Shared 4x4 safari vehicle',
      'Professional English-speaking guide',
      '3 nights budget lodge and camping accommodation',
      'Meals as specified',
      'Drinking water on game drives',
    ],
    excluded: [
      'International flights and Tanzania visa',
      'Travel insurance',
      'Drinks, tips, and personal expenses',
      'Optional activities',
    ],
    days: [
      day('', 'Day 1', 'Open departure', 'Tarangire National Park', 'Pickup in Arusha and a full day in Tarangire. Picnic lunch, afternoon game viewing, then lodge overnight.', {
        stay: 'Fig Tree Lodge',
        meals: 'Lunch and dinner',
        viewing: 'Full-day game drive',
        image: galleryPhoto('tarangire', 2),
      }),
      day('', 'Day 2', 'Open departure', 'Serengeti National Park', 'Drive through the Ngorongoro Conservation Area into the Serengeti. Afternoon game drive, then overnight at Nyani public campsite.', {
        stay: 'Nyani Public Campsite, Serengeti',
        viewing: 'Afternoon game drive',
        image: galleryPhoto('serengeti', 1),
      }),
      day('', 'Day 3', 'Open departure', 'Full day in the Serengeti', 'A full day on the plains with picnic lunch. Overnight at Simba public campsite on the crater rim.', {
        stay: 'Simba Public Campsite, crater rim',
        viewing: 'Full-day game drive',
        image: galleryPhoto('serengeti', 2),
      }),
      day('', 'Day 4', 'Open departure', 'Ngorongoro Crater and return', 'Descend into the crater for a game drive and picnic lunch, then drive back to Arusha.', {
        stay: 'Own arrangements / onward transfer',
        meals: 'Breakfast and lunch',
        viewing: 'Crater game drive',
        image: galleryPhoto('ngorongoro', 1),
      }),
    ],
  },
  {
    id: '5-day-shared-group-camping-safari',
    slug: '5-day-shared-group-camping-safari',
    title: '5 Day Shared Group Camping Safari',
    datesLabel: 'Open 2026–2027',
    start: '',
    end: '',
    duration: '5 Days / 4 Nights',
    places: 'Tarangire · Serengeti · Ngorongoro',
    image: galleryPhoto('serengeti', 3),
    style: 'wildlife',
    activity: 'Group Safari',
    featured: false,
    price_from: 1250,
    currency: 'USD',
    spaces: 'Public campsites · small group',
    deposit: 'Join group',
    tags: [
      { label: 'Camping', detail: 'Public campsites' },
      { label: 'Serengeti', detail: 'Two nights' },
      { label: 'Crater rim', detail: 'Simba campsite' },
    ],
    overview:
      'Five days on the Northern Circuit with public-campsite nights: Tarangire, two nights in the Serengeti, a crater-rim night at Simba, then Ngorongoro Crater before Arusha. Shared 4x4 and a professional English-speaking guide.',
    cta: 'Ask to join this 2026–2027 group safari — USD 1,250 per person.',
    highlights: [
      'Two nights camping in the Serengeti',
      'Ngorongoro crater-rim night',
      'Shared 4x4 and professional guide',
      'Park and crater fees included',
    ],
    included: [
      'Park entry fees and Ngorongoro crater fees',
      'Shared 4x4 safari vehicle with pop-up roof',
      'Professional English-speaking guide',
      '4 nights lodge and camping accommodation',
      'Meals as specified',
      'Drinking water on game drives',
      'Arusha pickup and drop-off',
    ],
    excluded: [
      'International and domestic flights',
      'Tanzania visa and travel insurance',
      'Drinks, tips, laundry, and souvenirs',
      'Optional activities',
    ],
    days: [
      day('', 'Day 1', 'Open departure', 'Arusha to Tarangire', 'Drive from Arusha to Tarangire for a full-day game drive. Overnight at a budget lodge near Karatu.', {
        stay: 'Kizumba / Fig Tree Lodge',
        meals: 'Lunch and dinner',
        viewing: 'Full-day game drive',
        image: galleryPhoto('tarangire', 3),
      }),
      day('', 'Day 2', 'Open departure', 'Into the Serengeti', 'Continue through the Northern Circuit into Serengeti National Park. Afternoon game drive, overnight at Nyani public campsite.', {
        stay: 'Nyani Public Campsite, Serengeti',
        viewing: 'Afternoon game drive',
        image: galleryPhoto('serengeti', 4),
      }),
      day('', 'Day 3', 'Open departure', 'Full day Serengeti', 'Full-day game drive with packed lunch. Return to Nyani public campsite.', {
        stay: 'Nyani Public Campsite, Serengeti',
        viewing: 'Full-day game drive',
        image: galleryPhoto('serengeti', 5),
      }),
      day('', 'Day 4', 'Open departure', 'Serengeti to Ngorongoro highlands', 'Morning game drive, then transfer to Simba public campsite on the crater rim.', {
        stay: 'Simba Public Campsite, crater rim',
        viewing: 'Morning game drive',
        image: galleryPhoto('ngorongoro', 2),
      }),
      day('', 'Day 5', 'Open departure', 'Ngorongoro Crater to Arusha', 'Descend into the crater for a game drive, then return to Arusha in the afternoon.', {
        stay: 'Own arrangements / onward transfer',
        meals: 'Breakfast and lunch',
        viewing: 'Crater game drive',
        image: galleryPhoto('ngorongoro', 3),
      }),
    ],
  },
  {
    id: '3-day-serengeti-ngorongoro-joining-safari',
    slug: '3-day-serengeti-ngorongoro-joining-safari',
    title: '3 Day Serengeti & Ngorongoro Joining Safari',
    datesLabel: 'Open 2026–2027',
    start: '',
    end: '',
    duration: '3 Days / 2 Nights',
    places: 'Serengeti · Ngorongoro',
    image: galleryPhoto('serengeti', 6),
    style: 'wildlife',
    activity: 'Group Safari',
    featured: false,
    price_from: 750,
    currency: 'USD',
    spaces: 'Two Serengeti nights',
    deposit: 'Join group',
    tags: [
      { label: 'Serengeti', detail: 'Two nights' },
      { label: 'Ngorongoro', detail: 'Crater game drive' },
    ],
    overview:
      'A short joining safari for travellers who want Serengeti and Ngorongoro without a private vehicle. Two nights in the Serengeti, a full day on the plains, then the crater before you return to Arusha.',
    cta: 'Ask to join this 2026–2027 group safari — USD 750 per person.',
    highlights: [
      'Two nights in the Serengeti',
      'Ngorongoro Crater game drive',
      'Shared 4x4 and professional guide',
      'Park and crater fees included',
    ],
    included: [
      'Park entry fees and Ngorongoro crater fees',
      'Shared 4x4 safari vehicle with pop-up roof',
      'Professional English-speaking guide',
      '2 nights camping accommodation',
      'Meals as specified',
      'Drinking water on game drives',
      'Arusha pickup and drop-off',
    ],
    excluded: [
      'Flights, visa, and travel insurance',
      'Drinks, tips, laundry, and souvenirs',
      'Personal expenses',
    ],
    days: [
      day('', 'Day 1', 'Open departure', 'Arusha to Serengeti', 'Drive into the Serengeti for an afternoon game drive. Overnight at Nyani public campsite.', {
        stay: 'Nyani Public Campsite, Serengeti',
        meals: 'Lunch and dinner',
        viewing: 'Afternoon game drive',
        image: galleryPhoto('serengeti', 7),
      }),
      day('', 'Day 2', 'Open departure', 'Full day Serengeti', 'Full-day game drive with packed lunch. Overnight again at Nyani public campsite.', {
        stay: 'Nyani Public Campsite, Serengeti',
        viewing: 'Full-day game drive',
        image: galleryPhoto('serengeti', 8),
      }),
      day('', 'Day 3', 'Open departure', 'Ngorongoro Crater to Arusha', 'Transfer to Ngorongoro, crater-floor game drive, then return to Arusha.', {
        stay: 'Own arrangements / onward transfer',
        meals: 'Breakfast and lunch',
        viewing: 'Crater game drive',
        image: galleryPhoto('ngorongoro', 4),
      }),
    ],
  },
  {
    id: '2-day-tarangire-ngorongoro-joining-safari',
    slug: '2-day-tarangire-ngorongoro-joining-safari',
    title: '2 Day Tarangire & Ngorongoro Joining Safari',
    datesLabel: 'Open 2026–2027',
    start: '',
    end: '',
    duration: '2 Days / 1 Night',
    places: 'Tarangire · Ngorongoro',
    image: galleryPhoto('tarangire', 4),
    style: 'wildlife',
    activity: 'Group Safari',
    featured: false,
    price_from: 500,
    currency: 'USD',
    spaces: 'One lodge night',
    deposit: 'Join group',
    tags: [
      { label: 'Tarangire', detail: 'Full-day game drive' },
      { label: 'Ngorongoro', detail: 'Crater morning' },
    ],
    overview:
      'Two days from Arusha for travellers with limited time: a full day in Tarangire, one lodge night, then Ngorongoro Crater before the evening drop-off in town.',
    cta: 'Ask to join this 2026–2027 group safari — USD 500 per person.',
    highlights: [
      'Tarangire and Ngorongoro in two days',
      'One night lodge accommodation',
      'Shared 4x4 and professional guide',
      'Park and crater fees included',
    ],
    included: [
      'Park entry fees and Ngorongoro crater fees',
      'Shared 4x4 safari vehicle with pop-up roof',
      'Professional English-speaking guide',
      '1 night budget lodge accommodation',
      'Meals as specified',
      'Drinking water on game drives',
      'Arusha pickup and drop-off',
    ],
    excluded: [
      'Flights, visa, and travel insurance',
      'Drinks, tips, and personal expenses',
      'Optional activities',
    ],
    days: [
      day('', 'Day 1', 'Open departure', 'Arusha to Tarangire', 'Full-day game drive in Tarangire with picnic lunch. Overnight at Fig Tree Lodge.', {
        stay: 'Fig Tree Lodge',
        meals: 'Lunch and dinner',
        viewing: 'Full-day game drive',
        image: galleryPhoto('tarangire', 5),
      }),
      day('', 'Day 2', 'Open departure', 'Ngorongoro Crater to Arusha', 'Early start to the crater floor, picnic lunch, then drive back to Arusha.', {
        stay: 'Own arrangements / onward transfer',
        meals: 'Breakfast and lunch',
        viewing: 'Crater game drive',
        image: galleryPhoto('ngorongoro', 5),
      }),
    ],
  },
  {
    id: 'ngorongoro-day-trip-joining-safari',
    slug: 'ngorongoro-day-trip-joining-safari',
    title: 'Ngorongoro Day Trip Joining Safari',
    datesLabel: 'Open 2026–2027',
    start: '',
    end: '',
    duration: '1 Day',
    places: 'Ngorongoro',
    image: galleryPhoto('ngorongoro', 7),
    style: 'wildlife',
    activity: 'Group Safari',
    featured: false,
    price_from: 250,
    currency: 'USD',
    spaces: 'No overnight · shared vehicle',
    deposit: 'Join group',
    tags: [
      { label: 'Day trip', detail: 'Return to Arusha' },
      { label: 'Crater floor', detail: 'Picnic lunch' },
    ],
    overview:
      'A one-day joining safari from Arusha into Ngorongoro Crater. Shared 4x4, professional English-speaking guide, picnic lunch, and evening drop-off in town — no overnight required.',
    cta: 'Ask to join this 2026–2027 day trip — USD 250 per person.',
    highlights: [
      'Ngorongoro Crater game drive',
      'Shared 4x4 and professional guide',
      'Picnic lunch included',
      'Same-day return to Arusha',
    ],
    included: [
      'Ngorongoro Conservation Area and crater fees',
      'Shared 4x4 safari vehicle with pop-up roof',
      'Professional English-speaking guide',
      'Picnic lunch and drinking water',
      'Arusha pickup and drop-off',
    ],
    excluded: [
      'Accommodation in Arusha',
      'Flights, visa, and travel insurance',
      'Drinks, tips, and personal expenses',
    ],
    days: [
      day('', 'Day 1', 'Open departure', 'Arusha to Ngorongoro Crater and return', 'Early pickup in Arusha, descend into the crater for a game drive and picnic lunch, then return to Arusha in the evening.', {
        stay: 'No overnight',
        meals: 'Picnic lunch',
        viewing: 'Crater game drive',
        transport: 'Shared 4x4 safari vehicle',
        image: galleryPhoto('ngorongoro', 8),
      }),
    ],
  },
];

assignUniqueCovers(openJoiningPackages);
