import { media as GM } from '../home/content.js';

/**
 * Original Golden Memories journal pieces.
 * Topics follow common Tanzania travel questions; wording, itineraries, and photos are GMS.
 */
export const rewrittenJournalArticles = [
  {
    slug: 'first-tanzania-safari-tips',
    topic: 'safari',
    date: '17 September 2026',
    title: 'First Tanzania safari: what we tell guests before they fly',
    excerpt: 'Pace, packing, park gates, and why a private vehicle changes a first game drive.',
    image: GM.ngorongoroTourists,
    paragraphs: [
      'A first safari is tiring in a good way: early starts, new light, and more animals than you can photograph. We plan a hotel night in Arusha after Kilimanjaro Airport so you are not climbing into a 4x4 still wearing the long-haul flight.',
      'Keep the first full day simple. Tarangire or a crater descent beats stacking three parks before you have learned how a game-drive morning works. Your driver-guide sets the rhythm, toilet stops, binocular time, and when to sit still at a sighting.',
      'Dust, sun, and cold crater dawns all show up in the same week. Neutral clothes, a warm layer, and closed shoes do more than a new khaki wardrobe. We send a packing note with the confirmation, including malaria advice to take to your own doctor.',
      'Write to us with the month you can travel and who is in the vehicle. We will say whether six days is enough, or whether you should protect an extra Serengeti night instead of adding a fourth park.',
    ],
  },
  {
    slug: 'one-week-tanzania-safari',
    topic: 'safari',
    date: '16 September 2026',
    title: 'How we spend one week on a Tanzania safari',
    excerpt: 'Northern classics when you have seven days, and when the south is the kinder fit.',
    image: GM.northern,
    paragraphs: [
      'Seven days from Arusha is enough for a real northern circuit if we do not pretend you can “do everything.” A shape we like: Tarangire, two or three Serengeti nights, and a Ngorongoro crater day, with hotel bookends in town.',
      'If the calendar puts wildebeest in the far north, we would rather fly one leg than spend two days on the road. If the herds are on the southern plains, driving the circuit still earns its keep, those hours are game viewing, not dead transfer.',
      'A southern week looks different: Nyerere (Selous) for water and wild dog country, or Ruaha for baobabs, lion, and space. Those parks sit closer to Dar es Salaam flights, which can suit a beach finish on Zanzibar without a long northern road.',
      'Tell us whether the week must include the crater, the migration, or a swim at the end. We cut parks before we cut sleep.',
    ],
  },
  {
    slug: 'tanzania-honeymoon-safari-and-beach',
    topic: 'safari',
    date: '15 September 2026',
    title: 'Planning a Tanzania honeymoon: safari first, then the island',
    excerpt: 'Private vehicle, a slower lodge night, and enough Zanzibar days that it still feels like a holiday.',
    image: GM.zanzibarBeach,
    paragraphs: [
      'Most couples who write to us want both: animals in the morning light and a few idle days in the Indian Ocean. We almost always put safari first. Dust, early starts, and park gates belong at the beginning; swimming belongs at the end.',
      'A private 4x4 is the honeymoon difference. You stop for a long elephant sighting, skip a crowded picnic site, and are not sharing the last row with strangers. Tent or lodge is taste: canvas close to the grass, or a more solid room after a long flight.',
      'On the island, decide whether you need all-tide swimming (north-west Unguja) or quieter east-coast sand. Stone Town is one night of doors and rooftops, not a beach. Pemba or Mafia only if you want diving more than a simple rest.',
      'Eight to twelve days is the range that usually feels generous. Shorter than that, we shorten the safari rather than the beach, or the other way around, if wildlife is the whole point. Share your dates; we will draw one itinerary, not two glued together.',
    ],
  },
  {
    slug: 'north-or-south-tanzania-safari',
    topic: 'safari',
    date: '14 September 2026',
    title: 'Northern or southern Tanzania: how we choose a circuit',
    excerpt: 'Famous parks and easy Arusha logistics in the north; quieter bush and different flights in the south.',
    image: GM.southern,
    paragraphs: [
      'The north is what most first-timers picture: Tarangire baobabs, the Ngorongoro crater, and Serengeti grassland, with Kilimanjaro Airport and our Arusha office close by. Roads, airstrips, and lodges are denser. In peak months you will share some sightings.',
      'The south is bigger country and fewer vehicles. Nyerere has rivers, boats, and wild dog. Ruaha is dry woodland, lion, and elephant, with camps that can feel like the only tent for miles. Logistics usually run through Dar es Salaam rather than Arusha.',
      'Choose north if time is tight and the classic names matter. Choose south if you want hush more than a crater postcard. Plenty of trips do a short north, then fly south or to the coast. We price the flying honestly before you decide.',
    ],
  },
  {
    slug: 'ngorongoro-crater-pros-and-cons',
    topic: 'safari',
    date: '13 September 2026',
    title: 'Ngorongoro crater: why we still go, and what we warn you about',
    excerpt: 'Dense wildlife on a caldera floor, a busy midday, and how we time a descent from Arusha.',
    image: GM.ngorongoro,
    paragraphs: [
      'The crater is a collapsed volcano with a lake, grassland, and forest on the floor. In one day you can see lion, buffalo, elephant, hippo, and, if you are fortunate, black rhino. That concentration is why we still put it on most northern itineraries.',
      'It is also a small stage. Vehicles gather at sightings, picnic sites fill, and the descent and ascent eat clock. We enter early, take a proper loop, and do not promise a second crater day unless you have a specific reason.',
      'Nights belong on the rim, not the floor. It is cold at dawn even in the dry season. Some camps sit further into the conservation area; those cost more in driving but give you Maasai highland country, not only the tourist road.',
      'If you hate crowds, we still use the crater as a bookend and give extra nights to Serengeti or Tarangire. Skipping it entirely makes sense only when time is very short or rhino is not on your list. Say so and we will plan around it.',
    ],
  },
  {
    slug: 'walking-safari-tanzania',
    topic: 'safari',
    date: '12 September 2026',
    title: 'Walking safaris in Tanzania: when we add them',
    excerpt: 'Tracks, wind, and armed rangers, a different hour from the roof hatch.',
    image: GM.savanna,
    paragraphs: [
      'A walk is not a substitute for a game drive. You cover less ground and you will not chase a cheetah. You do learn how animals use a drainage line, and you notice dung, birds, and the smell of crushed grass that you miss from a vehicle.',
      'Where walks are allowed, they run with a trained guide and an armed ranger. Parks and concessions set the rules. The crater floor is not a walking circuit; parts of the Serengeti, Tarangire concessions, Nyerere, and Ruaha can be, depending on camp and season.',
      'We add a walk when guests are steady on their feet and the camp runs it well. Families with small children and anyone who wants maximum cats in a short week usually stay in the vehicle.',
      'Ask when you book, not at the fire the night before. Permits and start times are arranged in advance, and some walks leave before breakfast.',
    ],
  },
  {
    slug: 'green-season-tanzania-safari',
    topic: 'safari',
    date: '11 September 2026',
    title: 'Green season in Tanzania: rain, birds, and quieter roads',
    excerpt: 'March to May is not a write-off. It is a different safari, with honest caveats.',
    image: GM.manyara,
    paragraphs: [
      'The long rains usually sit around March to May. Grass grows, skies go dramatic, and some remote camps close because roads cut up. What stays open can feel like a private park compared with August.',
      'Birdlife is excellent. Calving may still echo in the south early in the season. Predators hunt in longer grass, so sightings take more patience. You will want waterproofs and a sense of humour about afternoon storms.',
      'We only sell green-season dates when the itinerary still works: lodges that stay open, parks whose roads we trust, and guests who care more about space than a guaranteed river crossing.',
      'If your leave is locked to April, write anyway. We would rather reshape the trip than pretend it is July.',
    ],
  },
  {
    slug: 'wildebeest-calving-season',
    topic: 'wildlife',
    date: '10 September 2026',
    title: 'Wildebeest calving on the southern Serengeti plains',
    excerpt: 'Short grass, newborns, and predators, a migration chapter that is not a river crossing.',
    image: GM.migration,
    paragraphs: [
      'From roughly December to March the southern Serengeti and Ndutu plains hold the herds for calving. The grass is short, the light is clean, and lion, cheetah, and hyena work the same country as the wildebeest.',
      'This is not the Mara River postcard. It is thousands of animals on open ground, and days that can change with a storm. We place camps in the south for these months rather than hoping a central Serengeti lodge will do.',
      'January and February are the weeks many photographers ask for. We still do not promise a particular hunt. We promise time in the right sector, a flexible game-drive plan, and honesty if the herds have already drifted.',
      'Pair calving with a crater day and a Tarangire night if you have the days. The north of the Serengeti can wait for another year.',
    ],
  },
  {
    slug: 'mara-river-crossings',
    topic: 'wildlife',
    date: '9 September 2026',
    title: 'Mara River crossings: how we talk about them',
    excerpt: 'July to October in the north, no appointment on the bank, extra nights if this is the goal.',
    image: GM.migration,
    paragraphs: [
      'Crossings happen when the herds decide to move, not when a brochure says Tuesday. In a typical year the northern Serengeti sees the drama between July and October. Crocodiles, steep banks, and hesitation make the spectacle, and also the waiting.',
      'We put you in the Kogatende area with spare mornings. One crossing can take hours to develop; some days the animals drink and turn around. A two-night dash from the crater is how people miss it and feel cheated.',
      'Flights into the north save road days when the herds are up there. Bag weight is strict. We would rather you pack a soft duffel than arrive late because a suitcase missed the Cessna.',
      'If your dates fall outside the crossing window, we say so. The Serengeti is still worth the journey for resident cats and space. We will not sell a “guaranteed crossing.”',
    ],
  },
  {
    slug: 'migration-month-by-month',
    topic: 'wildlife',
    date: '8 September 2026',
    title: 'Where the migration usually is, month by month',
    excerpt: 'A working calendar we adjust with current reports, not a promise for your exact week.',
    image: GM.migration,
    paragraphs: [
      'January to March: southern plains and Ndutu, calving, short grass. April and May: herds drift west and north as the long rains green the western corridor; roads can be heavy. June: groups mass toward the Grumeti and western woodlands.',
      'July and August: the north and the Mara River become the story. September and October: crossings can continue, then the turn south begins. November: short rains pull animals toward the eastern and southern plains. December: the south fills again.',
      'Rain does not read this paragraph. A wet Kenya or a dry Ndutu will move the front of the herd. We book camps by season, then refine with the week’s reports from our guides.',
      'Use this as a starting map when you email us. We will answer with the sector we would actually sleep in for your dates.',
    ],
  },
  {
    slug: 'endemic-wildlife-tanzania',
    topic: 'wildlife',
    date: '7 September 2026',
    title: 'Wildlife you only meet in Tanzania',
    excerpt: 'From giraffe subspecies to island colobus, the animals that make this country specific.',
    image: GM.tarangire,
    paragraphs: [
      'Guests come for lion and elephant. We also point out what is Tanzanian in a quieter way: Masai giraffe on the northern circuit, the red colobus of Zanzibar’s Jozani forest, and the Udzungwa and Usambara mountains, which hold birds and primates you will not see on a Serengeti game drive.',
      'The crater’s black rhino are not endemic, but they are scarce, and this is one of the better places in East Africa to look. Wild dog in Nyerere and Ruaha are another reason to leave the north if you have the time.',
      'Ask if you care about a particular animal. We will match park and season instead of padding a list of Latin names.',
    ],
  },
  {
    slug: 'lions-in-tanzania',
    topic: 'wildlife',
    date: '6 September 2026',
    title: 'Where we look for lions on a Tanzania safari',
    excerpt: 'Crater floor, Serengeti prides, and Ruaha’s reputation, odds, not a checklist.',
    image: GM.northern,
    paragraphs: [
      'Lions use whatever cover and prey the season offers. On the crater floor you often find them in the open, used to vehicles. In the Serengeti they lie up on kopjes in the heat and hunt when the light goes gold.',
      'Tarangire’s dry-season concentration around the river can produce lion as well as elephant. Ruaha is famous among guides for large prides and a wilder feel, with fewer cars at a sighting.',
      'We do not drive past a good elephant moment to “find lion.” Cats are easier when you know the territories, which is why the same driver-guide over several days beats a new face every morning.',
      'If lions are your headline, we put extra nights in Serengeti or Ruaha and keep the crater as a supporting day. Photography hides and night drives only where the park rules allow.',
    ],
  },
  {
    slug: 'cheetahs-of-the-serengeti',
    topic: 'wildlife',
    date: '5 September 2026',
    title: 'Cheetah country: open Serengeti and the patience it takes',
    excerpt: 'Short grass, kopjes, and why a long sit beats a racing loop.',
    image: GM.savanna,
    paragraphs: [
      'Cheetahs need space and a view. The southern and eastern Serengeti plains, especially in the greener months after the short rains, are where we spend time scanning. A kopje at midday is a typical rest; a hunt, if it comes, is often in softer light.',
      'Other vehicles arrive quickly when a cat is found. A good guide leaves a sighting that has turned into a car park and looks for the next open pan. That is not rudeness; it is how you still see the animal behave.',
      'We cannot promise a kill. We can promise binoculars, time, and a driver who will wait rather than tick a box and leave.',
      'Namiri-style eastern grassland is one option among several; we choose camps by your month, not by a single famous name.',
    ],
  },
  {
    slug: 'tanzania-safari-vehicles',
    topic: 'safari',
    date: '4 September 2026',
    title: 'Open sides or pop-up roof: safari vehicles we actually use',
    excerpt: 'Photography, dust, crater rules, and why a private 4x4 is the real upgrade.',
    image: GM.tarangire,
    paragraphs: [
      'Most of our northern game drives are in 4x4s with a pop-up roof: shade when you need it, standing room for photographs, and sides that keep dust and sun under control. Fully open vehicles exist in some concessions; they are brilliant for cameras and colder on a crater dawn.',
      'Ngorongoro has its own rules about vehicle type and crowding. We match the car to the park, not to a photo from another country. In the south, some camps use open game-viewers on private land and closed cars on public roads.',
      'Sharing a vehicle on a join-safari departure keeps the price down and means you agree the day’s plan with other guests. A private car is how families, photographers, and honeymooners set their own stops.',
      'Tell us if photography is the point. We will talk window seats, beanbags, and whether an open vehicle is worth the extra dust.',
    ],
  },
  {
    slug: 'tented-camp-or-lodge',
    topic: 'safari',
    date: '3 September 2026',
    title: 'Tented camp or lodge: how we match the night to the guest',
    excerpt: 'Canvas close to the bush, solid walls after a long flight, and mobile camps that follow the herds.',
    image: GM.selous,
    paragraphs: [
      'A proper safari tent is not a festival canvas. It has a bed, an en-suite, and usually a generator or solar hour for charging. You hear hyena at night. That is the point for many guests.',
      'Lodges and more permanent camps suit families, older travellers, and anyone who wants a swimming pool after the crater. Mixed itineraries work well: canvas in the Serengeti, a highland lodge on the rim.',
      'Mobile camps move with the migration a few times a year. They cost more to run and they put you in the right grass. We only recommend them when the season and your budget line up.',
      'We book rooms we have used or that our guides trust. Send us a comfort level — “simple but clean” versus “I want a bath” — and we will not surprise you at check-in.',
    ],
  },
  {
    slug: 'kenya-or-tanzania-safari',
    topic: 'safari',
    date: '1 September 2026',
    title: 'Kenya or Tanzania: the comparison we give from Arusha',
    excerpt: 'Mara versus Serengeti, crater versus no crater, and why many trips never need both countries.',
    image: GM.northern,
    paragraphs: [
      'Both countries hold the same migration system. Kenya’s Masai Mara is smaller and, in peak crossing weeks, busier. Tanzania’s Serengeti is vast; camp location matters more than the park stamp in your passport.',
      'Tanzania adds Ngorongoro, Kilimanjaro, and a straightforward Zanzibar beach finish. Kenya adds the Mara, Amboseli’s elephant-and-Kilimanjaro views from the other side, and different flight hubs. Neither is “better”; they are different weeks.',
      'We are a Tanzanian operator. If your heart is set on the Mara, we will say so rather than force a northern circuit. If you want one country, one visa, and a crater day, stay with us.',
      'Crossing both borders in a single holiday is possible and tiring. Most guests are happier with extra nights in one ecosystem.',
    ],
  },
  {
    slug: 'how-tanzania-safari-prices-work',
    topic: 'about-tanzania',
    date: '30 August 2026',
    title: 'What actually sits inside a Tanzania safari price',
    excerpt: 'Park fees, vehicles, lodges, and why a cheap day can become an expensive week.',
    image: GM.dayTrip,
    paragraphs: [
      'A safari quote is mostly three things: park and concession fees, the vehicle and guide, and the bed. Fees are set by the authorities and move. Lodges cost more in July than in April. Flying between airstrips is a fourth line when we use it.',
      'Join-safari seats look cheaper because you share the car. Private trips cost more and buy the day. Children, single rooms, and Christmas dates change the maths. We show the pieces so you can see where to save, fewer parks, shoulder season, or a simpler camp, without hiding a park fee.',
      'International flights, visas, tips, drinks, and some activities sit outside the package unless we say otherwise. Light-aircraft baggage limits are not a surprise we spring at the airstrip.',
      'Ask for a quote with your month and party size. We would rather send a clear number than a headline “from” that only works for two people in November.',
    ],
  },
  {
    slug: 'nyerere-and-ruaha',
    topic: 'safari',
    date: '28 August 2026',
    title: 'Nyerere and Ruaha: the southern parks we send people to',
    excerpt: 'Rivers and wild dog in one; baobabs and lion in the other, and how they pair with Zanzibar.',
    image: GM.southern,
    paragraphs: [
      'Nyerere National Park (the former Selous) is water and woodland: boats on the lakes, walks where allowed, and a wild dog population that keeps guides talking. It sits closer to Dar, which can make a beach add-on simpler than a northern road safari.',
      'Ruaha is drier, bigger, and famous for lion, elephant, and kudu among baobabs. Camps can feel remote. Flying in is normal. Combining both parks in one week is a strong southern safari if you accept the extra airstrip.',
      'Dry months concentrate game on remaining water. Green months are lush and slower. We match camp to season the same way we do in the Serengeti.',
      'If you have already done the crater and want fewer vehicles, start here. If it is your first Africa trip and you only have five days, we still often begin in the north.',
    ],
  },
  {
    slug: 'mafia-island-whale-sharks',
    topic: 'islands',
    date: '27 August 2026',
    title: 'Mafia Island: whale sharks, quiet reefs, and a slower coast',
    excerpt: 'When we send guests past Zanzibar for snorkelling and village pace.',
    image: GM.coast,
    paragraphs: [
      'Mafia sits south of Unguja. The marine park is the reason to go: reefs, green turtles, and, in the right months, whale sharks that snorkellers meet on the surface. It is not a party beach.',
      'The season for sharks is typically around October to March, weather and plankton deciding the week. We do not guarantee an encounter. We do book operators who treat the animals as wild, not props.',
      'Getting there is a hop from Dar or Zanzibar. Pair Mafia with a southern safari more naturally than with a long northern circuit, unless you have two full weeks.',
      'If you only want sunloungers, stay on Zanzibar. If you want water with a purpose, ask us for Mafia nights.',
    ],
  },
  {
    slug: 'pemba-after-safari',
    topic: 'islands',
    date: '25 August 2026',
    title: 'Pemba Island after safari: diving, cloves, and fewer hotels',
    excerpt: 'A greener island than Unguja, for guests who want reefs more than a beach bar.',
    image: GM.spice,
    paragraphs: [
      'Pemba is hillier and quieter than Zanzibar’s main island. Clove farms, mangrove creeks, and serious dive sites are the draw. Resorts are fewer; transfers take longer; that is the trade.',
      'We send divers and couples who have already seen Stone Town and want hush. First-time beach guests usually sleep better on Unguja, where swimming and spa days are simpler to arrange.',
      'Flights and boats need buffer time after a Serengeti airstrip. We do not book Pemba as a single night squeezed between Kilimanjaro and a homebound flight.',
      'Tell us your dive certification and how many idle days you have. If the answer is two, we stay on Zanzibar.',
    ],
  },
  {
    slug: 'stone-town-before-the-beach',
    topic: 'islands',
    date: '24 August 2026',
    title: 'Stone Town before the beach: one night that earns its keep',
    excerpt: 'Doors, waterfront, and spice history, then transfer to sand when you have had enough lanes.',
    image: GM.spice,
    paragraphs: [
      'Stone Town is a stone-and-coral city of alleys, carved doors, and a harbour that has seen dhows for centuries. It is humid, busy, and worth an evening rooftop even if you came only to swim.',
      'We usually give it one night, sometimes two if you care about history. A guided walk beats getting lost with a suitcase. The beach hotel should be a separate chapter, not a day-trip from town.',
      'Jozani Forest’s red colobus is a stop on the way to the east or south coast if you want a last wild hour before the tide takes over.',
      'Skip Stone Town if rest is the only goal after Kilimanjaro. Keep it if you want the island to feel like Zanzibar, not only a resort brand.',
    ],
  },
  {
    slug: 'tanzania-culture-and-food',
    topic: 'about-tanzania',
    date: '23 August 2026',
    title: 'Culture at the table: Swahili, ugali, and a respectful village visit',
    excerpt: 'What we eat on the road, and how a cultural stop should feel, not a performance.',
    image: GM.cultureTeam,
    paragraphs: [
      'Swahili is the welcome. A few words, mambo, asante, pole pole, go a long way with the crew. English is widely spoken in lodges; markets and village visits are kinder when you try.',
      'On the plate: ugali, nyama choma, pilau, fresh mango, and Zanzibar spices. Safari lodges serve international menus because guests need calories; ask for local dishes if you want them. Street food is for town days, with the usual care about water and unpeeled fruit.',
      'A Maasai or Hadzabe visit should be arranged so the community is paid and the stop is not a zoo. We brief you on photographs and gifts. If you would rather spend the hour with elephants, we skip it.',
      'Our tagline is “Your Culture or Ours.” That is an invitation to share a meal and a story, not to costume you for a picture.',
    ],
  },
  {
    slug: 'what-to-see-in-arusha',
    topic: 'about-us',
    date: '22 August 2026',
    title: 'A night in Arusha before the parks',
    excerpt: 'Airport rest, the market, and why we do not treat town as wasted time.',
    image: GM.cultureTeam,
    paragraphs: [
      'Arusha is where we live and where most northern trips begin. After Kilimanjaro Airport you want a shower and a bed more than a city tour. We still like a slow morning: coffee, a craft market if you have energy, or Arusha National Park if you landed early and cannot sit still.',
      'Mount Meru hangs over town. On a clear day it reminds you the “safari” has already started. Njiro, where our office sits, is residential and practical, good for last-minute kit, not for nightlife.',
      'We can arrange a cultural or coffee stop on the way toward Moshi or the northern parks. We will not fill a rest day with five attractions because a blog said you must.',
      'If you have a spare afternoon on the way home, say so. Otherwise we protect sleep. The crater will still be there at dawn.',
    ],
  },
  {
    slug: 'olduvai-gorge',
    topic: 'about-tanzania',
    date: '19 August 2026',
    title: 'Olduvai Gorge: a short stop with a long human story',
    excerpt: 'On the road between the crater highlands and the Serengeti, if the clock allows.',
    image: GM.savanna,
    paragraphs: [
      'Olduvai (Oldupai) Gorge sits on the usual driving line toward the Serengeti. It is a paleoanthropology site, early stone tools and hominin fossils, not a game-drive loop. A guided museum stop of an hour or two is enough for most guests.',
      'We add it when the transfer day has slack and someone in the vehicle cares about human origins. We skip it when the migration is moving and you would rather spend the light on the plains.',
      'There is a fee, a bit of sun, and not much shade. Bring water and the same hat you use on safari.',
      'Ask when you book. It is an easy yes or no on the itinerary, not a surprise roadside stall.',
    ],
  },
  {
    slug: 'safari-for-older-travellers',
    topic: 'safari',
    date: '14 August 2026',
    title: 'Safari at an easier pace: older travellers, joints, and long days',
    excerpt: 'Shorter drives, the right room, and a crater dawn that still feels possible.',
    image: GM.ngorongoroTourists,
    paragraphs: [
      'Age is not a reason to stay home. Long corrugations, high step-ins, and 5 a.m. starts are. We plan fewer parks, lodges with proper bathrooms, and a vehicle you can enter without a gymnastic moment.',
      'The crater rim is cold and the descent is a road, not a hike. Serengeti airstrips cut the worst driving. Walking safaris are optional; most guests this pace never miss them.',
      'Medical kit, insurance that covers evacuation, and honest talk about mobility happen before we take a deposit. We would rather adjust the trip than have you suffer a full-day bump to the western corridor.',
      'Families spanning three generations are some of our favourite vehicles. The private car is what makes that work.',
    ],
  },
  {
    slug: 'zanzibar-snorkelling-and-diving',
    topic: 'islands',
    date: '13 August 2026',
    title: 'Snorkelling and diving after a Tanzania safari',
    excerpt: 'Mnemba, east-coast reefs, and when Mafia or Pemba is the better water.',
    image: GM.zanzibarBeach,
    paragraphs: [
      'Unguja’s easiest snorkel is often a boat to the reefs off the north-east, weather and park rules permitting. East-coast tides change the day: low water can mean a long walk before you swim. North-west beaches are kinder for a casual dip.',
      'Qualified divers get more from Pemba or Mafia than from a single Zanzibar tourist dive. We book operators who brief currents and do not chase wildlife with a motor.',
      'After Kilimanjaro, wait a day before you dive. Residual fatigue and altitude do not mix with a deep site. Safari-only guests can snorkel sooner.',
      'Tell us certification level and whether you want one fun boat or a proper dive week. The island plan changes with that answer.',
    ],
  },
  {
    slug: 'three-tanzania-itineraries',
    topic: 'safari',
    date: '7 August 2026',
    title: 'Three itineraries we actually draw from Arusha',
    excerpt: 'A first-timer’s north, a migration focus, and a safari-and-beach finish, starting points, not brochures.',
    image: GM.safariPackages,
    paragraphs: [
      'Classic north, eight days: Arusha rest, Tarangire, Serengeti, Ngorongoro crater, back to town. Driving, private 4x4, lodges mixed with one tented night if you want canvas. This is the trip we send most first-timers on.',
      'Migration focus, nine or ten days: fly or drive to the sector that holds the herds that month, extra nights there, crater as a bookend, skip a fourth park. Photographers live here.',
      'Safari and beach, ten to twelve days: the classic north in compressed form, then a flight to Zanzibar for Stone Town plus a north-west beach. Knees from Kilimanjaro get a hotel night before any of it.',
      'None of these is fixed. Dates, children, and budget move the nights. Write to us; we will not paste a PDF with someone else’s camp names.',
    ],
  },
  {
    slug: 'money-and-tipping-in-tanzania',
    topic: 'about-tanzania',
    date: '5 August 2026',
    title: 'Cash, cards, and tipping on a Tanzania safari',
    excerpt: 'US dollars that look new, a little shilling for town, and how we brief crew gratuities.',
    image: GM.dayTrip,
    paragraphs: [
      'Lodges and our invoices are usually in US dollars. Bring notes that are recent and undamaged; old bills get refused. Tanzanian shillings help in markets, taxis, and small restaurants in Arusha or Stone Town.',
      'Cards work in larger hotels and some town ATMs. Bush camps may be cash-only for drinks and curios. We say so in the joining notes. Do not rely on an ATM at Naabi Hill.',
      'Tipping is customary, not a surprise levy. We suggest ranges for driver-guides, porters on Kilimanjaro, and lodge staff, in cash at the end. You are free to give more or less; we will not collect a mandatory “tip jar” into a black box.',
      'Keep a copy of your passport and a card in a separate pouch. Phones and cameras stay in the vehicle’s dry box when we say so, dust is expensive.',
    ],
  },
  {
    slug: 'tanzania-safari-accommodation-styles',
    topic: 'safari',
    date: '31 July 2026',
    title: 'Safari beds: public-park lodges, special camps, and the crater rim',
    excerpt: 'What “inside the park” means for fees, atmosphere, and the 6 a.m. start.',
    image: GM.ngorongoroAlt,
    paragraphs: [
      'Inside Serengeti or Tarangire you pay park fees for every night and you hear the grass. Outside, on the rim or in a conservation area, you may drive into the park at dawn. Both can be excellent. The wrong choice is a cheap room so far out that you burn the golden hour on tarmac.',
      'Ngorongoro rim lodges are about the view and the cold. Crater-floor camping is restricted and not what most private trips do. Highlands camps trade a longer transfer for space.',
      '“Luxury” in Tanzania is more about guiding, location, and privacy than thread count. A famous international brand is one option; a well-run Tanzanian camp can be the better night.',
      'We pick rooms to match the itinerary, not to fill a partner quota. If you have a lodge you already love, tell us and we will build around it when it sits in the right park.',
    ],
  },
  {
    slug: 'what-to-do-in-tanzania',
    topic: 'about-tanzania',
    date: '3 July 2026',
    title: 'What to do in Tanzania besides the obvious game drive',
    excerpt: 'Parks, mountain, coast, and the extras we add only when they earn a day.',
    image: GM.hero,
    paragraphs: [
      'The core is still a wildlife safari. Around it: Kilimanjaro or Meru if you want a trek, Zanzibar or Mafia if you want salt water, and a cultural visit if you want conversation more than another picnic site.',
      'Hot air balloons over the Serengeti, a night in a mobile camp, a boat in Nyerere, or chimpanzee tracking in the west are extras with their own cost and weather risk. We add them when they are the reason you came, not as decoration.',
      'Day trips from Arusha, Materuni waterfall, a coffee farm, Lake Manyara, suit short stays or the afternoon after you land. They are not a substitute for two nights in the Serengeti.',
      'Start with how many days you have. We will say what fits, and what should wait for the next ticket.',
    ],
  },
  {
    slug: 'insect-bites-and-malaria-on-safari',
    topic: 'about-tanzania',
    date: '24 June 2026',
    title: 'Mosquitoes, tsetse, and the medical chat we cannot skip',
    excerpt: 'Repellent, clothing, and why your doctor, not a blog, chooses malaria tablets.',
    image: GM.manyara,
    paragraphs: [
      'Malaria is present in much of Tanzania, including safari circuits and the coast. Prophylaxis is a conversation with a travel clinic. We are guides, not prescribers. Start that visit early; some tablets need a run-in.',
      'Cover ankles at dusk, use the net over the bed, and pack a repellent you already tolerate. Tsetse flies in some woodland bite through thin shirts; a heavier long sleeve helps more than perfume.',
      'Yellow fever certificates depend on your routing. We flag this in pre-departure notes. Keep prescription medicines in original boxes in your daypack, not the porter duffel.',
      'If you have severe allergies or a heart condition, tell us before we assign a remote camp. Evacuation insurance is part of travelling here, not an upsell.',
    ],
  },
  {
    slug: 'rhino-in-ngorongoro',
    topic: 'wildlife',
    date: '18 June 2026',
    title: 'Black rhino on the crater floor',
    excerpt: 'Why this is one of the better looks in Tanzania, and why we still speak in odds.',
    image: GM.ngorongoro,
    paragraphs: [
      'Eastern black rhino survive in small numbers in the Ngorongoro Conservation Area. A crater loop gives you a real chance compared with most of the Serengeti, especially with a guide who knows which sector they used that week.',
      'You will look from a distance. That is conservation, not a failed game drive. Binoculars matter more than a phone zoom.',
      'Poaching and slow breeding keep the numbers fragile. Park rules, vehicle limits, and patience are part of seeing them at all.',
      'If rhino is your one animal, say so. We still cannot write it on a guarantee card. We can put the crater on a day with a decent weather window and a guide who will linger.',
    ],
  },
  {
    slug: 'tanzania-facts-for-travellers',
    topic: 'about-tanzania',
    date: '12 June 2026',
    title: 'Tanzania in brief, for people about to pack',
    excerpt: 'Equator, Swahili, parks, and the mountain, the facts that actually affect a trip.',
    image: GM.hero,
    paragraphs: [
      'Tanzania sits just south of the equator, on the Indian Ocean, with Kilimanjaro as Africa’s highest peak. The commercial capital is Dar es Salaam; the safari capital we work from is Arusha. Zanzibar is part of the same United Republic.',
      'English and Swahili will get you through a lodge. The shilling is the local currency; safari quotes often run in dollars. Plugs are typically British-style; a spare camera battery still earns its place.',
      'More than a third of the land is under some form of protection, parks, reserves, conservation areas. That is why a week can feel like several countries.',
      'The rest is for the itinerary: your dates, your knees, and whether you want canvas or a swimming pool. We will not quiz you on independence year at the airport.',
    ],
  },
];
