export const accommodationsHero = {
  image: "/images/accommodations/hero.webp",
};

export const lodges = [
  {
    name: "Njiro Legacy Hotel",
    place: "Arusha · Njiro",
    region: "Arusha",
    category: "midrange",
    blurb: "A quieter Njiro stay with Meru views, used for arrival and last nights when you want space away from town traffic.",
    website: "https://www.njirolegacy.com/",
    image: "/images/accommodations/njiro-legacy-hotel.webp",
    gallery: ["/images/accommodations/njiro-legacy-hotel-2.webp","/images/accommodations/njiro-legacy-hotel-3.webp"],
  },
  {
    name: "Gold Crest Hotel",
    place: "Arusha",
    region: "Arusha",
    category: "midrange",
    blurb: "A practical Arusha hotel with a pool, used before and after northern-circuit days.",
    website: "https://www.goldcresthotel.com/",
    image: "/images/accommodations/gold-crest-hotel.webp",
    gallery: ["/images/accommodations/gold-crest-hotel-2.webp","/images/accommodations/gold-crest-hotel-3.webp"],
  },
  {
    name: "Venus Premier Hotel",
    place: "Arusha",
    region: "Arusha",
    category: "midrange",
    blurb: "A comfortable city hotel on the Arusha road network for the night before safari.",
    website: "https://venuspremierhotel.com/",
    image: "/images/accommodations/venus-premier-hotel.webp",
    gallery: ["/images/accommodations/venus-premier-hotel-2.webp","/images/accommodations/venus-premier-hotel-3.webp"],
  },
  {
    name: "Ang'ata Tarangire Camp",
    place: "Tarangire",
    region: "Tarangire",
    category: "midrange",
    blurb: "Canvas rooms among baobabs on the Tarangire circuit, elephant country and a mess tent after the drive.",
    website: "https://www.angatacamps.com/",
    image: "/images/accommodations/angata-tarangire-camp.webp",
    gallery: ["/images/accommodations/angata-tarangire-camp-2.webp","/images/accommodations/angata-tarangire-camp-3.webp"],
  },
  {
    name: "Tarangire Tortilis Camp",
    place: "Tarangire",
    region: "Tarangire",
    category: "midrange",
    blurb: "A tented camp among baobabs on the Tarangire circuit, elephant country and big-sky evenings.",
    website: "https://www.tortiliscamps.com/tarangire-tortilis-camp/",
    image: "/images/accommodations/tarangire-tortilis-camp.webp",
    gallery: ["/images/accommodations/tarangire-tortilis-camp-2.webp","/images/accommodations/tarangire-tortilis-camp-3.webp"],
  },
  {
    name: "Tarangire Safari Lodge",
    place: "Tarangire",
    region: "Tarangire",
    category: "midrange",
    blurb: "Since 1985, family-owned & managed Tarangire Safari Lodge has been well known for its location and panoramic views. We have catered to wildlife enthusiasts and those seeking rest and relaxation among one of Tanzania’s most popular national parks.",
    website: "https://www.tarangiresafarilodge.com/",
    image: "/images/accommodations/tarangire-safari-lodge.webp",
    gallery: ["/images/accommodations/tarangire-safari-lodge-2.webp","/images/accommodations/tarangire-safari-lodge-3.webp"],
  },
  {
    name: "Suricata Boma Lodge",
    place: "Lake Manyara",
    region: "Lake Manyara",
    category: "midrange",
    blurb: "Two majestic centenary baobabs greet you as you arrive at Suricata Boma Lodge. Ideally situated between key national parks, our lodge offers breathtaking",
    website: "https://suricatabomalodge.com/",
    image: "/images/accommodations/suricata-boma-lodge.webp",
    gallery: ["/images/accommodations/suricata-boma-lodge-2.webp","/images/accommodations/suricata-boma-lodge-3.webp"],
  },
  {
    name: "Sound of Silence Manyara",
    place: "Lake Manyara",
    region: "Lake Manyara",
    category: "midrange",
    blurb: "Tented nights with escarpment and lake-circuit access, canvas rooms when you want a quieter Manyara stay.",
    website: "https://serengetisoundofsilence.com/",
    image: "/images/accommodations/sound-of-silence-manyara.webp",
    gallery: ["/images/accommodations/sound-of-silence-manyara-2.webp","/images/accommodations/sound-of-silence-manyara-3.webp"],
  },
  {
    name: "Safari Haven Serengeti Camp",
    place: "Serengeti",
    region: "Serengeti",
    category: "midrange",
    blurb: "A tented Serengeti camp for game-drive days on the plains, with canvas rooms close to the wildlife circuits.",
    website: "https://safarihavencamp.com/",
    image: "/images/accommodations/safari-haven-serengeti-camp.webp",
    gallery: ["/images/accommodations/safari-haven-serengeti-camp-2.webp","/images/accommodations/safari-haven-serengeti-camp-3.webp"],
  },
  {
    name: "Ang'ata Serengeti Camp",
    place: "Serengeti",
    region: "Serengeti",
    category: "midrange",
    blurb: "A mobile-feel tented camp placed for Serengeti game-drive days, canvas rooms and a mess tent in the bush.",
    website: "https://www.angatacamps.com/",
    image: "/images/accommodations/angata-serengeti-camp.webp",
    gallery: ["/images/accommodations/angata-serengeti-camp-2.webp","/images/accommodations/angata-serengeti-camp-3.webp"],
  },
  {
    name: "Tukaone Serengeti Camp",
    place: "Serengeti",
    region: "Serengeti",
    category: "midrange",
    blurb: "Tukaone Camps offer an exclusive gateway to the heart of Serengeti National Park. These Camps blend modern comfort with authentic wilderness experiences,",
    website: "https://tukaonecamps.com/",
    image: "/images/accommodations/tukaone-serengeti-camp.webp",
    gallery: ["/images/accommodations/tukaone-serengeti-camp-2.webp","/images/accommodations/tukaone-serengeti-camp-3.webp"],
  },
  {
    name: "Marera Valley Lodge",
    place: "Karatu · Ngorongoro highlands",
    region: "Ngorongoro / Karatu",
    category: "midrange",
    blurb: "Cottages and lawns in Karatu, a quiet highland base for Ngorongoro Crater mornings.",
    website: "https://marreravalleylodge.com/",
    image: "/images/accommodations/marera-valley-lodge.webp",
    gallery: ["/images/accommodations/marera-valley-lodge-2.webp","/images/accommodations/marera-valley-lodge-3.webp"],
  },
  {
    name: "Farm of Dreams Lodge",
    place: "Karatu · Ngorongoro highlands",
    region: "Ngorongoro / Karatu",
    category: "midrange",
    blurb: "The Lodge is located in the tourist town of Karatu on the Western south Slopes of Ngorongoro Crater at the 1,400 feet above sea level; the Lodge sits in a garden of flowers and vegetables. The property offers spectacular sweeping views of the hills and close distant to the Ngorongoro Crater, Lake Eyasi, Lake Manyara and Tarangire National Park.",
    website: "https://farmofdreamslodge.com/",
    image: "/images/accommodations/farm-of-dreams-lodge.webp",
    gallery: ["/images/accommodations/farm-of-dreams-lodge-2.webp","/images/accommodations/farm-of-dreams-lodge-3.webp"],
  },
  {
    name: "Ang'ata Ngorongoro Camp",
    place: "Ngorongoro",
    region: "Ngorongoro / Karatu",
    category: "midrange",
    blurb: "Tented highland nights near the crater rim, used when you want canvas before an early crater descent.",
    website: "https://www.angatacamps.com/",
    image: "/images/accommodations/angata-ngorongoro-camp.webp",
    gallery: ["/images/accommodations/angata-ngorongoro-camp-2.webp","/images/accommodations/angata-ngorongoro-camp-3.webp"],
  },
  {
    name: "Mama Dunia Safari Lodge",
    place: "Karatu · Ngorongoro highlands",
    region: "Ngorongoro / Karatu",
    category: "midrange",
    blurb: "Our lodge is nestled in Karatu, the heart of Tanzania’s main safari parks, harmoniously blending with the natural beauty of the Tanzanian landscape. Let us guide you through the essence of our lodge surounded by towering trees provide inviting spots for relaxation and reflection.",
    website: "https://mamaduniasafarilodge.co.tz/",
    image: "/images/accommodations/mama-dunia-safari-lodge.webp",
    gallery: ["/images/accommodations/mama-dunia-safari-lodge-2.webp","/images/accommodations/mama-dunia-safari-lodge-3.webp"],
  },
  {
    name: "Kibo Palace Hotel",
    place: "Arusha",
    region: "Arusha",
    category: "luxury",
    blurb: "A fuller Arusha hotel stay, rooms, dining, and a pool for arrival or last nights on a luxury circuit.",
    website: "https://kibopalacehotel.com/",
    image: "/images/accommodations/kibo-palace-hotel.webp",
    gallery: ["/images/accommodations/kibo-palace-hotel-2.webp","/images/accommodations/kibo-palace-hotel-3.webp"],
  },
  {
    name: "Mount Meru Hotel",
    place: "Arusha",
    region: "Arusha",
    category: "luxury",
    blurb: "A landmark Arusha hotel with gardens and a pool, used when you want a proper city night before safari.",
    website: "https://www.mountmeruhotel.co.tz/",
    image: "/images/accommodations/mount-meru-hotel.webp",
    gallery: ["/images/accommodations/mount-meru-hotel-2.webp","/images/accommodations/mount-meru-hotel-3.webp"],
  },
  {
    name: "Manyara's Secret",
    place: "Tarangire & Lake Manyara",
    region: "Tarangire & Lake Manyara",
    category: "luxury",
    blurb: "Luxury and nature come together in a unique place in Tanzania. At Manyara’s Secret, you’ll enjoy breathtaking views over Lake Manyara, where elephants, monkeys, and tree-climbing lions roam close by. From our exclusive boutique lodge, you can experience the magic of Africa, with safari opportunities in:",
    website: "https://manyarassecret.com/",
    image: "/images/accommodations/manyara-s-secret.webp",
    gallery: ["/images/accommodations/manyara-s-secret-2.webp","/images/accommodations/manyara-s-secret-3.webp"],
  },
  {
    name: "Oliver's Camp / Kuro Treetops",
    place: "Tarangire",
    region: "Tarangire",
    category: "luxury",
    blurb: "Asilia’s Tarangire camps, walking country, baobabs, and tented rooms placed for the park’s quieter southern circuits.",
    website: "https://www.asiliaafrica.com/camps/olivers-camp/",
    image: "/images/accommodations/oliver-s-camp-kuro-treetops.webp",
    gallery: ["/images/accommodations/oliver-s-camp-kuro-treetops-2.webp","/images/accommodations/oliver-s-camp-kuro-treetops-3.webp"],
  },
  {
    name: "Mawe Mawe Manyara Lodge",
    place: "Lake Manyara",
    region: "Lake Manyara",
    category: "luxury",
    blurb: "Mawe Mawe Lodge offers a once-in-a-lifetime experience in northern Tanzania, featuring luxury villas with beautiful views of Lake Manyara National Park.",
    website: "https://mawemawemanyaralodge.com/",
    image: "/images/accommodations/mawe-mawe-manyara-lodge.webp",
    gallery: ["/images/accommodations/mawe-mawe-manyara-lodge-2.webp","/images/accommodations/mawe-mawe-manyara-lodge-3.webp"],
  },
  {
    name: "Sametu Camp",
    place: "Serengeti",
    region: "Serengeti",
    category: "luxury",
    blurb: "Discover the magic of Serengeti at Sametu Camp. While here embark on game drives that take you into the realm of legends, an undisturbed serenity...Book now!",
    website: "https://karibucamps.com/sametu-camp/",
    image: "/images/accommodations/sametu-camp.webp",
    gallery: ["/images/accommodations/sametu-camp-2.webp","/images/accommodations/sametu-camp-3.webp"],
  },
  {
    name: "Serengeti Serena Safari Lodge",
    place: "Serengeti",
    region: "Serengeti",
    category: "luxury",
    blurb: "Serengeti Serena Safari Lodge blended high into an acacia-lined ridge, our African-style lodge, infinity pool offer panoramic views across the Serengeti plains",
    website: "https://www.serenahotels.com/serengeti",
    image: "/images/accommodations/serengeti-serena-safari-lodge.webp",
    gallery: ["/images/accommodations/serengeti-serena-safari-lodge-2.webp","/images/accommodations/serengeti-serena-safari-lodge-3.webp"],
  },
  {
    name: "Kubu Kubu Tented Lodge",
    place: "Serengeti",
    region: "Serengeti",
    category: "luxury",
    blurb: "A Tanganyika Wilderness Camps tented lodge in the Serengeti, used for luxury canvas nights on the circuit.",
    website: "https://twctanzania.com/lodges/",
    image: "/images/accommodations/kubu-kubu-tented-lodge.webp",
    gallery: ["/images/accommodations/kubu-kubu-tented-lodge-2.webp","/images/accommodations/kubu-kubu-tented-lodge-3.webp"],
  },
  {
    name: "Ole Serai Luxury Camps (Turner Springs)",
    place: "Serengeti",
    region: "Serengeti",
    category: "luxury",
    blurb: "A Wellworth Collection camp at Turner Springs, luxury tents for Serengeti game-drive days.",
    website: "https://wellworthcollection.co.tz/ole-serai-luxury-camp-turner-springs/",
    image: "/images/accommodations/ole-serai-luxury-camps-turner-springs.webp",
    gallery: ["/images/accommodations/ole-serai-luxury-camps-turner-springs-2.webp","/images/accommodations/ole-serai-luxury-camps-turner-springs-3.webp"],
  },
  {
    name: "Moyo Tented Camp",
    place: "Serengeti",
    region: "Serengeti",
    category: "luxury",
    blurb: "Experience authentic safaris in the heart of Tanzania. Moyo Tented Camp offers luxury canvas accommodations, game drives, cultural visits, and front-row views of the Great Migration in the Serengeti’s Seronera region.",
    website: "https://www.moyotentedcamp.com/",
    image: "/images/accommodations/moyo-tented-camp.webp",
    gallery: ["/images/accommodations/moyo-tented-camp-2.webp","/images/accommodations/moyo-tented-camp-3.webp"],
  },
  {
    name: "Nakupenda Luxury Camp",
    place: "Serengeti",
    region: "Serengeti",
    category: "luxury",
    blurb: "A small luxury Serengeti camp, tented rooms and a mess tent placed for wildlife circuits.",
    website: "https://nakupendacamps.com/",
    image: "/images/accommodations/nakupenda-luxury-camp.webp",
    gallery: ["/images/accommodations/nakupenda-luxury-camp-2.webp","/images/accommodations/nakupenda-luxury-camp-3.webp"],
  },
  {
    name: "Lion's Paw Camp",
    place: "Ngorongoro",
    region: "Ngorongoro",
    category: "luxury",
    blurb: "A Karibu Camps tented stay on the crater rim, used for luxury nights before an early crater descent.",
    website: "https://karibucamps.com/awl_filter_gallery/lions-paw-camp/",
    image: "/images/accommodations/lion-s-paw-camp.webp",
    gallery: ["/images/accommodations/lion-s-paw-camp-2.webp","/images/accommodations/lion-s-paw-camp-3.webp"],
  },
  {
    name: "Ngorongoro Serena Safari Lodge",
    place: "Ngorongoro",
    region: "Ngorongoro",
    category: "luxury",
    blurb: "Ngorongoro Serena Safari Lodge is located in Tanzania’s Ngorongoro Crater, built into the Crater’s jagged rim, cloaked in river stone and indigenous vines",
    website: "https://www.serenahotels.com/ngorongoro",
    image: "/images/accommodations/ngorongoro-serena-safari-lodge.webp",
    gallery: ["/images/accommodations/ngorongoro-serena-safari-lodge-2.webp","/images/accommodations/ngorongoro-serena-safari-lodge-3.webp"],
  },
  {
    name: "Ngorongoro Oldeani Mountain Lodge",
    place: "Ngorongoro",
    region: "Ngorongoro",
    category: "luxury",
    blurb: "A Wellworth Collection highland lodge near Oldeani, used for luxury crater nights with mountain views.",
    website: "https://wellworthcollection.co.tz/ngorongoro-oldeani-mountain-lodge/",
    image: "/images/accommodations/ngorongoro-oldeani-mountain-lodge.webp",
    gallery: ["/images/accommodations/ngorongoro-oldeani-mountain-lodge-2.webp","/images/accommodations/ngorongoro-oldeani-mountain-lodge-3.webp"],
  },
  {
    name: "Gran Meliá Arusha",
    place: "Arusha",
    region: "Arusha",
    category: "premium-luxury",
    blurb: "Gran Meliá Arusha Hotel. Excellent service. ✔ Amazing views ✔ Complimentary Wi-Fi ✔ Gym ✔ Sauna ✔ Spa ✔ Wellness | Exclusive MeliáRewards discounts",
    website: "https://www.melia.com/en/hotels/tanzania/arusha/gran-melia-arusha",
    image: "/images/accommodations/gran-meli-arusha.webp",
    gallery: ["/images/accommodations/gran-meli-arusha-2.webp","/images/accommodations/gran-meli-arusha-3.webp"],
  },
  {
    name: "Lake Manyara Kilimamoja Lodge",
    place: "Tarangire & Lake Manyara",
    region: "Tarangire & Lake Manyara",
    category: "premium-luxury",
    blurb: "A Wellworth Collection lodge above the Rift, premium nights between Tarangire and Lake Manyara.",
    website: "https://wellworthcollection.co.tz/",
    image: "/images/accommodations/lake-manyara-kilimamoja-lodge.webp",
    gallery: ["/images/accommodations/lake-manyara-kilimamoja-lodge-2.webp","/images/accommodations/lake-manyara-kilimamoja-lodge-3.webp"],
  },
  {
    name: "Meliá Serengeti Lodge",
    place: "Serengeti",
    region: "Serengeti",
    category: "premium-luxury",
    blurb: "A hilltop Meliá lodge in the Serengeti, premium rooms and views for plains days.",
    website: "https://www.melia.com/en/hotels/tanzania/serengeti-national-park/hotel-serengeti-lodge-melia-collection",
    image: "/images/accommodations/meli-serengeti-lodge.webp",
    gallery: ["/images/accommodations/meli-serengeti-lodge-2.webp","/images/accommodations/meli-serengeti-lodge-3.webp"],
  },
  {
    name: "Serengeti Explorer",
    place: "Serengeti",
    region: "Serengeti",
    category: "premium-luxury",
    blurb: "An Elewana Collection camp in the Serengeti, premium tents placed for migration and resident-game months.",
    website: "https://www.elewanacollection.com/serengeti-explorer-camp",
    image: "/images/accommodations/serengeti-explorer.webp",
    gallery: ["/images/accommodations/serengeti-explorer-2.webp"],
  },
  {
    name: "Pioneer Camp",
    place: "Serengeti",
    region: "Serengeti",
    category: "premium-luxury",
    blurb: "Elewana’s Pioneer Camp in the Serengeti, a premium tented stay for game-drive days on the plains.",
    website: "https://www.elewanacollection.com/serengeti-pioneer-camp/at-a-glance",
    image: "/images/accommodations/pioneer-camp.webp",
    gallery: ["/images/accommodations/pioneer-camp-2.webp","/images/accommodations/pioneer-camp-3.webp"],
  },
  {
    name: "Four Seasons Safari Lodge Serengeti",
    place: "Serengeti",
    region: "Serengeti",
    category: "premium-luxury",
    blurb: "A flagship Serengeti lodge, used when the circuit should stay at the top of the range.",
    website: "https://www.fourseasons.com/serengeti/",
    image: "/images/accommodations/four-seasons-safari-lodge-serengeti.webp",
    gallery: ["/images/accommodations/four-seasons-safari-lodge-serengeti-2.webp","/images/accommodations/four-seasons-safari-lodge-serengeti-3.webp"],
  },
  {
    name: "Ngorongoro Lodge Meliá Collection",
    place: "Ngorongoro",
    region: "Ngorongoro",
    category: "premium-luxury",
    blurb: "A Meliá Collection lodge on the crater highlands, premium rooms for crater-morning circuits.",
    website: "https://www.melia.com/en/hotels/tanzania/ngorongoro-conservation-area/ngorongoro-lodge-melia-collection",
    image: "/images/accommodations/hero.webp",
    gallery: [],
  },
  {
    name: "The Manor at Ngorongoro",
    place: "Ngorongoro",
    region: "Ngorongoro",
    category: "premium-luxury",
    blurb: "Elewana’s manor-house lodge in the Karatu highlands, a premium night before or after the crater.",
    website: "https://elewanacollection.com/the-manor-at-ngorongoro",
    image: "/images/accommodations/the-manor-at-ngorongoro.webp",
    gallery: ["/images/accommodations/the-manor-at-ngorongoro-2.webp"],
  }
];
